services:
  app:
    build: .
    container_name: twbobibobi2025-app
    working_dir: /app
    volumes:
      - .:/app:delegated
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"